/* =========================================================
   NIEMCY.JS
   PEŁNA BAZA NIEMIECKICH KODÓW TABLIC REJESTRACYJNYCH

   Baza:
   - aktualne oznaczenia
   - przywrócone / historyczne Altkennzeichen
   - kody występujące nadal na drogach

   Format:
   KOD: "miasto / powiat"
   ========================================================= */

const NIEMCY_KODY = {

    /* =====================================================
       A
       ===================================================== */

    A: "Augsburg",
    AA: "Ostalbkreis (Aalen)",
    AB: "Aschaffenburg",
    ABG: "Altenburger Land",
    ABI: "Anhalt-Bitterfeld",
    AC: "Aachen",
    AE: "Auerbach",
    AH: "Ahaus",
    AIB: "Bad Aibling",
    AIC: "Aichach-Friedberg",
    AK: "Altenkirchen",
    AL: "Altena",
    ALF: "Alfeld (Leine)",
    ALS: "Alsfeld",
    ALZ: "Alzenau",
    AM: "Amberg",
    AN: "Ansbach",
    ANA: "Annaberg",
    ANG: "Angermünde",
    ANK: "Anklam",
    AÖ: "Altötting",
    AP: "Weimarer Land (Apolda)",
    APD: "Apolda",
    AR: "Arnsberg",
    ARN: "Arnstadt",
    ART: "Artern",
    ASD: "Aschendorf-Hümmling",
    AS: "Amberg-Sulzbach",
    ASL: "Aschersleben-Staßfurt",
    ASZ: "Aue-Schwarzenberg",
    AT: "Altentreptow",
    AU: "Aue",
    AUR: "Aurich",
    AW: "Ahrweiler",
    AZ: "Alzey-Worms",
    AZE: "Anhalt-Zerbst",


    /* =====================================================
       B
       ===================================================== */

    B: "Berlin",
    BA: "Bamberg",
    BAD: "Baden-Baden",
    BAR: "Barnim",
    BB: "Böblingen",
    BBG: "Bernburg",
    BC: "Biberach",
    BCH: "Buchen (Odenwald)",
    BE: "Beckum",
    BED: "Brand-Erbisdorf",
    BEI: "Beilngries",
    BEL: "Belzig",
    BER: "Bernau",
    BF: "Burgsteinfurt",
    BGD: "Berchtesgaden",
    BGL: "Berchtesgadener Land",
    BH: "Bühl",
    BI: "Bielefeld",
    BID: "Biedenkopf",
    BIN: "Bingen am Rhein",
    BIR: "Birkenfeld",
    BIT: "Bitburg-Prüm (Eifelkreis)",
    BIW: "Bischofswerda",
    BK: "Backnang / Landkreis Börde",
    BKS: "Bernkastel-Kues",
    BL: "Zollernalbkreis (Balingen)",
    BLB: "Berleburg",
    BLK: "Burgenlandkreis",
    BM: "Rhein-Erft-Kreis (Bergheim)",
    BN: "Bonn",
    BNA: "Borna",
    BO: "Bochum",
    BÖ: "Bördekreis",
    BOG: "Bogen",
    BOH: "Bocholt",
    BOR: "Borken",
    BOT: "Bottrop",
    BR: "Bruchsal",
    BRA: "Wesermarsch (Brake)",
    BRB: "Brandenburg",
    BRG: "Burg",
    BRI: "Brilon",
    BRK: "Bad Brückenau",
    BRL: "Blankenburg (Braunlage)",
    BRV: "Bremervörde",
    BS: "Braunschweig",
    BSB: "Bersenbrück",
    BSK: "Beeskow",
    BT: "Bayreuth",
    BTF: "Bitterfeld",
    BU: "Burgdorf",
    BÜD: "Büdingen",
    BÜR: "Büren",
    BÜS: "Büsingen (Konstanz)",
    BÜZ: "Bützow",
    BUL: "Burglengenfeld",
    BZ: "Bautzen",
    BZA: "Bergzabern",


    /* =====================================================
       C
       ===================================================== */

    C: "Chemnitz",
    CA: "Calau",
    CAS: "Castrop-Rauxel",
    CB: "Cottbus",
    CE: "Celle",
    CHA: "Cham",
    CLP: "Cloppenburg",
    CLZ: "Clausthal-Zellerfeld",
    CO: "Coburg",
    COC: "Cochem-Zell",
    COE: "Coesfeld",
    CR: "Crailsheim",
    CUX: "Cuxhaven",
    CW: "Calw",


    /* =====================================================
       D
       ===================================================== */

    D: "Düsseldorf",
    DA: "Darmstadt",
    DAH: "Dachau",
    DAN: "Lüchow-Dannenberg",
    DAU: "Daun",
    DBR: "Bad Doberan",
    DD: "Dresden",
    DE: "Dessau-Roßlau",
    DEG: "Deggendorf",
    DEL: "Delmenhorst",
    DGF: "Dingolfing-Landau",
    DH: "Diepholz",
    DI: "Dieburg",
    DIL: "Dillkreis (Dillenburg)",
    DIN: "Dinslaken",
    DIZ: "Diez",
    DKB: "Dinkelsbühl",
    DL: "Döbeln",
    DLG: "Dillingen an der Donau",
    DM: "Demmin",
    DN: "Düren",
    DO: "Dortmund",
    DON: "Donau-Ries (Donauwörth)",
    DS: "Donaueschingen",
    DT: "Lippe (Detmold)",
    DU: "Duisburg",
    DUD: "Duderstadt",
    DÜW: "Bad Dürkheim",
    DW: "Dippoldiswalde",
    DZ: "Delitzsch",


    /* =====================================================
       E
       ===================================================== */

    E: "Essen",
    EA: "Eisenach",
    EB: "Eilenburg",
    EBE: "Ebersberg",
    EBN: "Ebern",
    EBS: "Ebermannstadt",
    ECK: "Eckernförde",
    ED: "Erding",
    EE: "Elbe-Elster",
    EF: "Erfurt",
    EG: "Eggenfelden",
    EH: "Eisenhüttenstadt",
    EHI: "Ehingen (Donau)",
    EI: "Eichstätt",
    EIC: "Eichsfeld",
    EIH: "Eichstätt",
    EIL: "Eisleben",
    EIN: "Einbeck",
    EIS: "Eisenberg",
    EL: "Emsland",
    EM: "Emmendingen",
    EMD: "Emden",
    EMS: "Rhein-Lahn-Kreis (Bad Ems)",
    EN: "Ennepe-Ruhr-Kreis",
    ER: "Erlangen",
    ERB: "Odenwaldkreis (Erbach)",
    ERH: "Erlangen-Höchstadt",
    ERK: "Erkelenz",
    ERZ: "Erzgebirgskreis",
    ES: "Esslingen",
    ESB: "Eschenbach in der Oberpfalz",
    ESA: "Eisenach",
    ESW: "Werra-Meißner-Kreis (Eschwege)",
    EU: "Euskirchen",
    EUT: "Eutin",
    EW: "Eberswalde",


    /* =====================================================
       F
       ===================================================== */

    F: "Frankfurt am Main",
    FAL: "Fallingbostel",
    FB: "Wetteraukreis (Friedberg)",
    FD: "Fulda",
    FDB: "Friedberg",
    FDS: "Freudenstadt",
    FEU: "Feuchtwangen",
    FF: "Frankfurt (Oder)",
    FFB: "Fürstenfeldbruck",
    FG: "Mittelsachsen (Freiberg)",
    FH: "Main-Taunus-Kreis (Frankfurt/Main-Höchst)",
    FI: "Finsterwalde",
    FKB: "Frankenberg (Eder)",
    FL: "Flensburg",
    FLÖ: "Flöha",
    FN: "Bodenseekreis (Friedrichshafen)",
    FO: "Forchheim",
    FOR: "Forst",
    FR: "Freiburg im Breisgau",
    FRG: "Freyung-Grafenau",
    FRI: "Friesland",
    FRW: "Bad Freienwalde",
    FS: "Freising",
    FT: "Frankenthal",
    FTL: "Freital",
    FÜ: "Fürth",
    FÜS: "Füssen",
    FW: "Fürstenwalde",
    FZ: "Fritzlar-Homberg",


    /* =====================================================
       G
       ===================================================== */

    G: "Gera",
    GA: "Gardelegen",
    GAN: "Bad Gandersheim",
    GAP: "Garmisch-Partenkirchen",
    GC: "Glauchau",
    GD: "Schwäbisch Gmünd",
    GDB: "Gadebusch",
    GE: "Gelsenkirchen",
    GEL: "Geldern",
    GEM: "Gmünden am Main",
    GEO: "Gerolzhofen",
    GER: "Germersheim",
    GF: "Gifhorn",
    GG: "Groß-Gerau",
    GHA: "Geithain",
    GHC: "Gräfenhainichen",
    GI: "Gießen",
    GK: "Geilenkirchen-Heinsberg",
    GL: "Rheinisch-Bergischer Kreis (Bergisch Gladbach)",
    GLA: "Gladbeck",
    GM: "Oberbergischer Kreis (Gummersbach)",
    GMN: "Grimmen",
    GN: "Gelnhausen",
    GNT: "Genthin",
    GOA: "Sankt Goar",
    GÖ: "Göttingen",
    GOH: "St. Goarshausen",
    GP: "Göppingen",
    GR: "Görlitz",
    GRA: "Grafenau",
    GRH: "Großenhain",
    GRI: "Bad Griesbach im Rottal",
    GRM: "Grimma",
    GRS: "Gransee",
    GRZ: "Greiz",
    GS: "Goslar",
    GT: "Gütersloh",
    GTH: "Gotha",
    GUB: "Guben",
    GÜ: "Güstrow",
    GUN: "Gunzenhausen",
    GV: "Grevenbroich",
    GVM: "Grevesmühlen",
    GW: "Vorpommern-Greifswald",
    GZ: "Günzburg",


    /* =====================================================
       H
       ===================================================== */

    H: "Hannover",
    HA: "Hagen",
    HAB: "Hammelburg",
    HAL: "Halle (Saale)",
    HAM: "Hamm",
    HAS: "Haßberge (Haßfurt)",
    HB: "Bremen",
    HBN: "Hildburghausen",
    HBS: "Halberstadt",
    HC: "Hainichen",
    HCH: "Hechingen",
    HD: "Heidelberg",
    HDH: "Heidenheim",
    HDL: "Haldensleben",
    HE: "Helmstedt",
    HEB: "Hersbruck",
    HEF: "Hersfeld-Rotenburg",
    HEI: "Dithmarschen (Heide)",
    HER: "Herne",
    HET: "Hettstedt",
    HF: "Herford",
    HG: "Hochtaunuskreis (Bad Homburg)",
    HGN: "Hagenow",
    HGW: "Hansestadt Greifswald",
    HH: "Hamburg",
    HHM: "Hohenmölsen",
    HI: "Hildesheim",
    HIG: "Heiligenstadt",
    HIP: "Hilpoltstein",
    HK: "Heidekreis",
    HL: "Hansestadt Lübeck",
    HM: "Hameln-Pyrmont",
    HMÜ: "Hann. Münden",
    HN: "Heilbronn",
    HO: "Hof",
    HÖS: "Erlangen-Höchstadt",
    HOG: "Hofgeismar",
    HOH: "Hofheim in Unterfranken",
    HOL: "Holzminden",
    HOM: "Saarpfalz-Kreis (Homburg)",
    HOR: "Freudenstadt (Horb am Neckar)",
    HOT: "Hohenstein-Ernstthal",
    HP: "Bergstraße (Heppenheim)",
    HR: "Schwalm-Eder-Kreis (Homberg)",
    HRO: "Hansestadt Rostock",
    HS: "Heinsberg",
    HSK: "Hochsauerlandkreis",
    HST: "Hansestadt Stralsund",
    HU: "Hanau",
    HÜN: "Hünfeld",
    HUS: "Husum",
    HV: "Havelberg",
    HVL: "Havelland (Rathenow)",
    HW: "Halle (Westfalen)",
    HWI: "Hansestadt Wismar",
    HX: "Höxter",
    HY: "Hoyerswerda",
    HZ: "Landkreis Harz",


    /* =====================================================
       I
       ===================================================== */

    IGB: "St. Ingbert",
    IK: "Ilm-Kreis",
    IL: "Ilmenau",
    ILL: "Illertissen",
    IN: "Ingolstadt",
    IS: "Iserlohn",
    IZ: "Steinburg (Itzehoe)",


    /* =====================================================
       J
       ===================================================== */

    J: "Jena",
    JB: "Jüterbog",
    JE: "Jessen",
    JEV: "Friesland (Jever)",
    JL: "Jerichower Land",
    JÜL: "Jülich",


    /* =====================================================
       K
       ===================================================== */

    K: "Köln",
    KA: "Karlsruhe",
    KAR: "Main-Spessart (Karlstadt)",
    KB: "Waldeck-Frankenberg (Korbach)",
    KC: "Kronach",
    KE: "Kempten (Allgäu)",
    KEH: "Kelheim",
    KEL: "Kehl",
    KEM: "Kemnath",
    KF: "Kaufbeuren",
    KG: "Bad Kissingen",
    KH: "Bad Kreuznach",
    KI: "Kiel",
    KIB: "Donnersbergkreis (Kirchheimbolanden)",
    KK: "Kempen-Krefeld",
    KL: "Kaiserslautern",
    KLE: "Kleve",
    KLZ: "Klötze",
    KM: "Kamenz",
    KN: "Konstanz",
    KO: "Koblenz",
    KÖN: "Bad Königshofen im Grabfeld",
    KÖT: "Köthen",
    KÖZ: "Kötzting",
    KR: "Krefeld",
    KRU: "Krumbach",
    KS: "Kassel",
    KT: "Kitzingen",
    KU: "Kulmbach",
    KÜN: "Hohenlohekreis (Künzelsau)",
    KUS: "Kusel",
    KW: "Königs Wusterhausen",
    KY: "Kyritz",
    KYF: "Kyffhäuserkreis",


    /* =====================================================
       L
       ===================================================== */

    L: "Leipzig / ehemalig Lahn-Dill-Kreis",
    LA: "Landshut",
    LAN: "Dingolfing-Landau",
    LAT: "Vogelsbergkreis (Lauterbach)",
    LAU: "Nürnberger Land (Lauf)",
    LB: "Ludwigsburg",
    LBS: "Lobenstein",
    LBZ: "Lübz",
    LC: "Luckau",
    LD: "Landau in der Pfalz",
    LDK: "Lahn-Dill-Kreis (Wetzlar)",
    LDS: "Dahme-Spreewald",
    LE: "Lemgo",
    LEO: "Leonberg",
    LER: "Leer (Ostfriesland)",
    LEV: "Leverkusen",
    LF: "Laufen",
    LG: "Lüneburg",
    LH: "Lüdinghausen",
    LI: "Lindau (Bodensee)",
    LIB: "Bad Liebenwerda",
    LIF: "Lichtenfels",
    LIN: "Lingen (Ems)",
    LIP: "Lippe (Detmold)",
    LK: "Lübbecke",
    LL: "Landsberg am Lech",
    LM: "Limburg-Weilburg",
    LN: "Lübben",
    LÖ: "Lörrach",
    LÖB: "Löbau",
    LOH: "Lohr am Main",
    LOS: "Oder-Spree",
    LP: "Lippstadt",
    LR: "Lahr (Schwarzwald)",
    LRO: "Landkreis Rostock",
    LS: "Märkischer Kreis (Lüdenscheid)",
    LSZ: "Bad Langensalza",
    LU: "Ludwigshafen am Rhein",
    LÜD: "Lüdenscheid",
    LÜN: "Lünen",
    LUK: "Luckenwalde",
    LUP: "Ludwigslust-Parchim",
    LWL: "Ludwigslust",


    /* =====================================================
       M
       ===================================================== */

    M: "München",
    MA: "Mannheim",
    MAB: "Marienberg",
    MAI: "Mainburg",
    MAK: "Marktredwitz",
    MAL: "Mallersdorf",
    MAR: "Marktheidenfeld",
    MB: "Miesbach",
    MC: "Malchin",
    MD: "Magdeburg",
    ME: "Mettmann",
    MED: "Süderdithmarschen (Meldorf)",
    MEG: "Melsungen",
    MEI: "Meißen",
    MEK: "Mittlerer Erzgebirgskreis",
    MEL: "Melle",
    MEP: "Meppen",
    MER: "Merseburg",
    MES: "Hochsauerlandkreis (Meschede)",
    MET: "Mellrichstadt",
    MG: "Mönchengladbach",
    MGH: "Bad Mergentheim",
    MGN: "Meiningen",
    MH: "Mülheim an der Ruhr",
    MHL: "Mühlhausen",
    MI: "Minden-Lübbecke",
    MIL: "Miltenberg",
    MK: "Märkischer Kreis",
    MKK: "Main-Kinzig-Kreis",
    ML: "Mansfelder Land",
    MM: "Memmingen",
    MN: "Unterallgäu (Mindelheim)",
    MO: "Moers",
    MOD: "Marktoberdorf",
    MOL: "Märkisch-Oderland",
    MON: "Monschau",
    MOS: "Neckar-Odenwald-Kreis (Mosbach)",
    MQ: "Merseburg-Querfurt",
    MR: "Marburg-Biedenkopf",
    MS: "Münster",
    MSE: "Mecklenburgische Seenplatte",
    MSH: "Mansfeld-Südharz",
    MSP: "Main-Spessart (Karlstadt)",
    MST: "Mecklenburg-Strelitz",
    MT: "Westerwald (Montabaur)",
    MTK: "Main-Taunus-Kreis",
    MTL: "Muldentalkreis",
    MU: "München Landkreis",
    MUC: "München Stadt",
    MÜ: "Mühldorf am Inn",
    MÜB: "Münchberg",
    MÜL: "Müllheim",
    MÜN: "Münsingen (Württemberg)",
    MÜR: "Müritz",
    MW: "Mittweida",
    MY: "Mayen",
    MYK: "Mayen-Koblenz",
    MZ: "Mainz / Mainz-Bingen",
    MZG: "Merzig-Wadern",


    /* =====================================================
       N
       ===================================================== */

    N: "Nürnberg",
    NAB: "Nabburg",
    NAI: "Naila",
    NAU: "Nauen",
    NB: "Neubrandenburg",
    ND: "Neuburg-Schrobenhausen",
    NDH: "Nordhausen",
    NE: "Neuss / Rhein-Kreis Neuss",
    NEA: "Neustadt an der Aisch-Bad Windsheim",
    NEB: "Nebra",
    NEC: "Neustadt bei Coburg",
    NEN: "Neunburg vorm Wald",
    NES: "Rhön-Grabfeld",
    NEU: "Hochschwarzwald (Titisee-Neustadt)",
    NEW: "Neustadt an der Waldnaab",
    NF: "Nordfriesland (Husum)",
    NH: "Neuhaus",
    NI: "Nienburg (Weser)",
    NIB: "Südtondern (Niebüll)",
    NK: "Neunkirchen (Saar)",
    NM: "Neumarkt in der Oberpfalz",
    NMB: "Naumburg",
    NMS: "Neumünster",
    NÖ: "Nördlingen",
    NOH: "Grafschaft Bentheim (Nordhorn)",
    NOL: "Niederschlesischer Oberlausitzkreis",
    NOM: "Northeim",
    NOR: "Norden",
    NP: "Neuruppin",
    NR: "Neuwied",
    NRÜ: "Neustadt am Rübenberge",
    NT: "Nürtingen",
    NU: "Neu-Ulm",
    NVP: "Nordvorpommern",
    NW: "Neustadt an der Weinstraße",
    NWM: "Nordwestmecklenburg",
    NY: "Niesky",
    NZ: "Neustrelitz",


    /* =====================================================
       O
       ===================================================== */

    OA: "Oberallgäu",
    OAL: "Ostallgäu",
    OB: "Oberhausen",
    OBB: "Obernburg am Main",
    OBG: "Osterburg",
    OC: "Oschersleben",
    OCH: "Ochsenfurt",
    OD: "Stormarn (Bad Oldesloe)",
    OE: "Olpe",
    ÖHR: "Öhringen",
    OF: "Offenbach am Main",
    OG: "Ortenaukreis (Offenburg)",
    OH: "Ostholstein",
    OHA: "Osterode am Harz",
    OHV: "Oberhavel",
    OHZ: "Osterholz",
    OK: "Ohrekreis",
    OL: "Oldenburg",
    OLD: "Oldenburg in Holstein",
    OP: "Rhein-Wupper-Kreis (Opladen)",
    OPR: "Ostprignitz-Ruppin",
    OR: "Oranienburg",
    OS: "Osnabrück",
    OSL: "Oberspreewald-Lausitz",
    OTT: "Otterndorf",
    OTW: "Ottweiler",
    OVI: "Oberviechtach",
    OVL: "Obervogtland",
    OVP: "Ostvorpommern",
    OZ: "Oschatz",


    /* =====================================================
       P
       ===================================================== */

    P: "Potsdam",
    PA: "Passau",
    PAF: "Pfaffenhofen an der Ilm",
    PAN: "Rottal-Inn (Pfarrkirchen)",
    PAR: "Parsberg",
    PB: "Paderborn",
    PCH: "Parchim",
    PE: "Peine",
    PEG: "Pegnitz",
    PER: "Perleberg",
    PF: "Pforzheim",
    PI: "Pinneberg",
    PIR: "Sächsische Schweiz-Osterzgebirge (Pirna)",
    PK: "Pritzwalk",
    PL: "Plauen",
    PLÖ: "Plön",
    PM: "Potsdam-Mittelmark",
    PN: "Pößneck",
    PR: "Prignitz (Perleberg)",
    PRÜ: "Prüm",
    PS: "Pirmasens",
    PW: "Pasewalk",
    PZ: "Prenzlau",


    /* =====================================================
       Q
       ===================================================== */

    QFT: "Querfurt",
    QLB: "Quedlinburg",


    /* =====================================================
       R
       ===================================================== */

    R: "Regensburg",
    RA: "Rastatt",
    RC: "Reichenbach",
    RD: "Rendsburg-Eckernförde",
    RDG: "Ribnitz-Damgarten",
    RE: "Recklinghausen",
    REG: "Regen",
    REH: "Rehau",
    REI: "Bad Reichenhall",
    RG: "Riesa-Großenhain",
    RH: "Roth",
    RI: "Rinteln",
    RID: "Riedenburg",
    RIE: "Riesa",
    RL: "Rochlitz",
    RM: "Röbel (Müritz)",
    RN: "Rathenow",
    RO: "Rosenheim",
    ROD: "Roding",
    ROF: "Rotenburg an der Fulda",
    ROK: "Rockenhausen",
    ROL: "Rottenburg an der Laaber",
    ROS: "Rostock",
    ROT: "Rothenburg ob der Tauber",
    ROW: "Rotenburg (Wümme)",
    RP: "Rhein-Pfalz-Kreis",
    RS: "Remscheid",
    RSL: "Roßlau",
    RT: "Reutlingen",
    RU: "Rudolstadt",
    RÜD: "Rheingau-Taunus-Kreis",
    RÜG: "Rügen",
    RV: "Ravensburg",
    RW: "Rottweil",
    RY: "Rheydt",
    RZ: "Herzogtum Lauenburg (Ratzeburg)",


    /* =====================================================
       S
       ===================================================== */

    S: "Stuttgart",
    SAB: "Saarburg",
    SAD: "Schwandorf",
    SÄK: "Säckingen",
    SAN: "Stadtsteinach",
    SAW: "Altmarkkreis Salzwedel",
    SB: "Saarbrücken",
    SBG: "Strasburg",
    SBK: "Schönebeck",
    SC: "Schwabach",
    SCZ: "Schleiz",
    SDH: "Sondershausen",
    SDL: "Stendal",
    SDT: "Schwedt (Oder)",
    SE: "Segeberg",
    SEB: "Sebnitz",
    SEE: "Seelow",
    SEF: "Scheinfeld",
    SEL: "Selb",
    SF: "Sonthofen",
    SFA: "Soltau-Fallingbostel",
    SFB: "Senftenberg",
    SFT: "Staßfurt",
    SG: "Solingen",
    SGH: "Sangerhausen",
    SHA: "Schwäbisch Hall",
    SHG: "Schaumburg",
    SHK: "Saale-Holzland-Kreis",
    SHL: "Suhl",
    SI: "Siegen-Wittgenstein",
    SIG: "Sigmaringen",
    SIM: "Rhein-Hunsrück-Kreis (Simmern)",
    SK: "Saalekreis",
    SL: "Schleswig-Flensburg",
    SLE: "Schleiden",
    SLF: "Saalfeld-Rudolstadt",
    SLG: "Saulgau",
    SLK: "Salzlandkreis",
    SLN: "Schmölln",
    SLS: "Saarlouis",
    SLÜ: "Schlüchtern",
    SLZ: "Bad Salzungen",
    SM: "Schmalkalden-Meiningen",
    SMÜ: "Schwabmünchen",
    SN: "Schwerin",
    SNH: "Sinsheim",
    SO: "Soest",
    SOB: "Schrobenhausen",
    SOL: "Soltau",
    SÖM: "Sömmerda",
    SOG: "Schongau",
    SOK: "Saale-Orla-Kreis (Schleiz)",
    SON: "Sonneberg",
    SP: "Speyer",
    SPB: "Spremberg",
    SPN: "Spree-Neiße",
    SPR: "Springe",
    SR: "Straubing (-Bogen)",
    SRB: "Strausberg",
    SRO: "Stadtroda",
    ST: "Steinfurt",
    STA: "Starnberg",
    STB: "Sternberg",
    STD: "Stade",
    STE: "Staffelstein",
    STH: "Schaumburg-Lippe (Stadthagen)",
    STL: "Stollberg",
    STO: "Stockach",
    SU: "Rhein-Sieg-Kreis (Siegburg)",
    SÜW: "Südliche Weinstraße",
    SUL: "Sulzbach-Rosenberg",
    SW: "Schweinfurt",
    SWA: "Rheingau-Taunus-Kreis (Bad Schwalbach)",
    SY: "Grafschaft Hoya (Syke)",
    SZ: "Salzgitter",
    SZB: "Schwarzenberg",


    /* =====================================================
       T
       ===================================================== */

    TBB: "Main-Tauber-Kreis (Tauberbischofsheim)",
    TDO: "Torgau / Delitzsch / Oschatz",
    TE: "Tecklenburg",
    TET: "Teterow",
    TF: "Teltow-Fläming",
    TG: "Torgau",
    TIR: "Tirschenreuth",
    TO: "Torgau-Oschatz",
    TÖL: "Bad Tölz-Wolfratshausen",
    TÖN: "Eiderstedt (Tönning)",
    TP: "Templin",
    TR: "Trier",
    TS: "Traunstein",
    TT: "Tettnang",
    TÜ: "Tübingen",
    TUT: "Tuttlingen",


    /* =====================================================
       U
       ===================================================== */

    UE: "Uelzen",
    UEM: "Ueckermünde",
    ÜB: "Überlingen am Bodensee",
    UER: "Uecker-Randow",
    UFF: "Uffenheim",
    UH: "Unstrut-Hainich-Kreis",
    UL: "Ulm",
    UM: "Uckermark",
    UN: "Unna",
    USI: "Usingen",


    /* =====================================================
       V
       ===================================================== */

    V: "Vogtlandkreis",
    VAI: "Vaihingen an der Enz",
    VB: "Vogelsbergkreis",
    VEC: "Vechta",
    VER: "Verden",
    VG: "Vorpommern-Greifswald",
    VIB: "Vilsbiburg",
    VIE: "Viersen",
    VIT: "Viechtach",
    VK: "Völklingen",
    VL: "Villingen (Schwarzwald)",
    VOF: "Vilshofen",
    VOH: "Vohenstrauß",
    VR: "Vorpommern-Rügen",
    VS: "Schwarzwald-Baar-Kreis (Villingen-Schwenningen)",


    /* =====================================================
       W
       ===================================================== */

    W: "Wuppertal",
    WA: "Waldeck",
    WAF: "Warendorf",
    WAK: "Wartburgkreis",
    WAN: "Wanne-Eickel",
    WAR: "Warburg",
    WAT: "Wattenscheid",
    WB: "Wittenberg",
    WBG: "Wolfsburg",
    WBS: "Worbis",
    WD: "Wiedenbrück",
    WDA: "Werdau",
    WE: "Weimar",
    WEB: "Oberwesterwaldkreis (Westerburg)",
    WEG: "Wegscheid",
    WEL: "Weilburg",
    WEM: "Wesermünde (Bremerhaven)",
    WEN: "Weiden in der Oberpfalz",
    WER: "Wertingen",
    WES: "Wesel",
    WF: "Wolfenbüttel",
    WG: "Wangen im Allgäu",
    WHV: "Wilhelmshaven",
    WI: "Wiesbaden",
    WIL: "Wittlich",
    WIS: "Wismar",
    WIT: "Witten",
    WIZ: "Witzenhausen",
    WK: "Wittstock",
    WL: "Harburg (Winsen/Luhe)",
    WLG: "Wolgast",
    WM: "Weilheim-Schongau",
    WMS: "Wolmirstedt",
    WN: "Rems-Murr-Kreis (Waiblingen)",
    WND: "St. Wendel",
    WO: "Worms",
    WOB: "Wolfsburg",
    WOH: "Wolfhagen",
    WOL: "Wolfach",
    WOR: "Wolfratshausen",
    WOS: "Wolfstein",
    WR: "Wernigerode",
    WRN: "Waren",
    WS: "Wasserburg am Inn",
    WSF: "Weißenfels",
    WST: "Ammerland (Westerstede)",
    WSW: "Weißwasser",
    WT: "Waldshut",
    WTL: "Wittlage",
    WTM: "Wittmund",
    WÜ: "Würzburg",
    WÜM: "Waldmünchen",
    WUG: "Weißenburg-Gunzenhausen",
    WUN: "Wunsiedel",
    WUR: "Wurzen",
    WW: "Westerwaldkreis",
    WZ: "Wetzlar",
    WZL: "Wanzleben",


    /* =====================================================
       Z
       ===================================================== */

    Z: "Zwickau",
    ZE: "Zerbst",
    ZEL: "Zell (Mosel)",
    ZI: "Löbau-Zittau",
    ZIG: "Ziegenhain (Schwalm-Eder-Kreis)",
    ZP: "Zschopau",
    ZR: "Zeulenroda",
    ZS: "Zossen",
    ZW: "Zweibrücken",
    ZZ: "Zeitz"

};